M7R0
I/AlgebraicLODEsy6+%+create_iswG%'inv2evG%*create_eqG%.global_boundsG%(inv_heuG
%*create_isG%+create_SymG%*create_SAG%+invariantsG6-%(makesetG%$valG%'sumsetG%%
nsetG%'comp_BG%%mgcdG%&fix_LG%*ram_indexG%-intersect_BrG%)create_UG%)create_XG+
t+6%%"dG%"mG%"wG6'%"iG%"jG%"cG%#isG%#NiG6"6"C(>8(""!>8$7#-%$seqG6$FJ/%"kG;"""9%
>8&FT>8%FJ?(FFFTFTFF2FY,&FUFTFTFTC&?(FFFTFTFF2&FL6#FT,&9$FTFTFTC$@$/-%$addG6$*&
&FL6#FRFT&9&FfoFTFQF]oC$>&8'6#FWFL>FW,&FWFTFTFT>Fjn,&FjnFTFTFT>FjnFJ>FY""#?(FFF
TFTFF30FYFT0FYFfn@%2&FL6#FYF]oC$>F[q,&F[qFTFTFT>FYFTC$>F[qFJ>FY,&FYFTFTFT>F\p-%
&ArrayG6#7#-FO6$&F\pFfo/FR;FT,&FWFT!""FT6#QhzReturn~an~array~of~the~exponents~o
f~the~monomials~of~degree~'d'~on~'m'~variables~that~form~a~basis~of~a~weighted~
symmetric~product~with~weights~'w'.~The~degree~'d'~and~the~number~of~variables~
'm'~are~integers~and~'w'~is~an~array~of~length~m~of~integers.FFFF6$%6_thismodul
edefinitionGFF6#""$%*protectedGt+6(%"PG%"nGF=%"JG%#fIG%#xsG63%&tempcG%#acG%#dcG
F@FA%"lG%%liscG%&nliscG%(lisxyzcG%)nlisxyzcG%#EQG%#COG%%tempG%&SolscG%$PevG%+ev
aluationG%#djG6"FFC(>847#-FO6$-%'degreeG6#&9'6#F\p/F\p;FTFho>83<#-FO6$/&%#FIGF[
u&9(F[uF\u>FLF]o>FYFJ?(FFFTFTFF0FLFJC.>FW-Fgt6$FL<#-FO6$&9)F[u/F\pFS>8*-T%6%FWF
hoFbt>8+-_I.LinearAlgebraG6$Fgr%(_syslibG%-RowDimensionG6#Fgv>8,-Fiv6%FWFU7#-FO
6$FTFev>8--F^w6#Few>8.-%'MatrixG6$F\xF\w>8/-%'VectorG6#F\x?(FIFTFTF\w%%trueGC$>
80-%'expandG6#-%$mulG6$)Fit&&Fgv6#FIF[uF\u?(F\pFTFTF\xFjxC$>&F`x6$F\pFIF]y?(8)F
TFTFUFjx>F[z-%&coeffG6%F[z&Fdv6#F^z&&FewF[uFdz?(F\pFTFTF\xFjxC$>&FexF[uFL?(F^zF
TFTFUFjx>Fjz-Faz6%FjzFczFez>81-_F_w%,LinearSolveG6$F`xFex>FY,&FYFT-Fbo6$*&&F`[l
F[uFT-Fby6$)&FeuFgy&&FgvF[uFgy/FIF]uFT/F\p;FTF\wFT>FL-F_y6#,&FLFT-Fbo6$*&Fj[lFT
-Fby6$)&FjtFgyF_\lFa\lFTFb\lF`r>82-%)simplifyG6#-%%subsG6$F_uFY6#Q\elLet~'J'~be
~an~array~of~'m'~polynomials~on~the~'n'~variables~'xs'~and~'P'~be~a~polynomial~
in~the~algebra~generated~by~'J'.~The~procedure~inv2ev~returns~the~value~of~'P'~
when~the~polynomials~in~'J'~take~the~values~in~'fI'.~The~'n'~entries~of~the~arr
ay~'xs'~are~variables,~'J'~are~'m'~polinomials~in~the~variables~in~xs,~P~is~an~
element~in~the~algebra~generated~by~'J'~and~'fI'~are~'m'~values~for~the~polynom
ials~in~'J'.FFFF6&FdrFFF%%+create_iswG6#""'Fgrt+6(F[sF=F\sF]sF^s>%#DDG%1_Envdif
fopdomainG6<F@FAFRFcs%"FG%$FijG%$xijGFhs%%SolsG%"MGFBFbsFdsFesFfsFgsFisFjsF`sFa
sF[t%"LG%"vG%#csG%"tG%#DtG6"FFC4@$-%%typeG6$Fdv%'symbolGYQCdifferential~algebra
~not~specifiedFF>8=&FdvF[o>8<&Fdv6#Fdp>FI7#-FO6$&Fho6#FL/FL;FTF]o>F^z-Fbx6#F]o?
(FLFTFTF]oFjx?(FYFTFTF]oFjx>&F^z6$FLFY-%%diffG6$&FIFb`l&FguF\q>FgvFf`l>8:-Fb[l6
$F^z-Fgx6#7#-FO6$-F^al6$&FjtFb`lFj_lFc`l?(FLFTFTF]oFjx>&Fgv6$FLFT&FdalFb`l?(FLF
TFTF]oFjx?(FYFdpFTF]oFjx>&FgvF\al,&-Fbo6$*&-F^al6$&Fgv6$FL,&FYFTF`rFT&FguF]pFT&
Fgv6$FWFTFT/FWFd`lFT-F^al6$F^clFj_lFT>F\w-Fbx6$F]oF\o?(FLFTFTF]oFjx>&F\wFbbl&Fg
uFb`l?(FLFTFTF]oFjx?(FYFdpFTF\oFjx>&F\wF\alF^cl>Few-Fb[l6$F\w-FgxFg`l>F\x-%$lcm
G6#-FO6$-%&denomG6#&FewFb`l/FL;FTF\o>F`x-FO6$-F_y6#-Fb]l6#*&F\xFTF_elFTF`el>8;7
#-FO6$-Fiv6(&F`xF]pF]oFUFhoFjtFgu/FWFael>89-Fbo6$*&-%'factorG6#*&&F[flFb`lFT&F[
fl6#F\oF`rFT)Fg_l,&FLFTF`rFTFTF`el6#QahlLet~G~be~a~finite~linear~group~in~GL(C,
'n')~and~'xs'~an~array~of~'n'~variables.~Let~'J'~be~an~array~of~'m'~generators~
of~the~algebra~of~G-invariant~polynomials~on~the~variables~in~'xs'.~Let~C~be~a~
G-invariant~algebraic~curve~and~let~'fI'~be~an~array~of~'m'~polynomials~such~th
at~J[i]~|gr-->~fI[i]~is~a~model~of~C.~The~procedure~create_eq~returns~an~LODE~g
iven~as~a~operator~in~the~differential~algebra~'DD'~such~that~the~values~of~the
~invariants~'J'~of~this~LODE~are~'fI'.FFFF6&FdrFFF&%'inv2evG6#F\^lFgrt,6%%$L_1G
'Fg^l%%listG>F`^lFa^l6.%"QGF@FAFh^lF[s%"pG%&alphaG%"rG%"BG%#BrG%"xG%#DxG6"FFC0@
$-Fa_l6$FhoFc_lYFe_l>F`x&FhoF\`l>Fex&FhoF[o>Fa^l7$FexF`x>FLFT>F\p-Fiv6$F]oFho>F
I,&-%%nopsG6#&-&I(DEtoolsG6$FgrFaw6#%+convertAlgG6$-&F]jl6#%*diffop2deG6$F\p-%"
yG6#F`xFgjlF[oFTF`rFT>F^z-%(factorsG6$&F[jl6$FT,&FIFTFTFT^#FT?&FY&F^zF\`lFjxC'>
Fgv-%&solveG6#&FYF[o>F\w-T'6#-&F]jl6#%(gen_expG6&F\p%"TG/F`xFgv/.%,restrict_toG
<#.%(minimalG>Few-T)6%F^\mFIFU>F\x-T+6$FewF\w@%/-FhilFhxFJ>FLFJ>FL*&FLFT)Fi[m-%
%ceilG6#-%$minGFhxFT>F\w-F\\m6#-F_\m6&F\pFc\m/F`x%)infinityGFe\m>Few-F]]m6%Fb^m
FIFU>F\xF`]m@$Fd]m>FLFJ@%/FLFJ7$FLFJ7$FL-%$maxG6$,*Fj]mF`r-%$sumG6$*&F_rFT&FUF]
pFT/FW;FT-Fhil6#FU!"#-Fgt6#-F]elFb`lFT-Fgt6#-%&numerGFb`lF`rFJ6#QibmLet~'L_1'~b
e~a~linear~ordinary~differential~operator~in~the~differential~algebra~'DD'~and~
'M'~an~array~of~non-negative~integers~m_0,...,m_|frn-1|hr.~The~procedure~global
_bounds~returns~a~rational~function~Q~and~an~integer~N~such~that~every~rational
~solution~y~of~Sym(|frL^(0)|hr^Sym(m_0),...,|frL^(n-1)|hr^Sym(m_|frn-1|hr))~can
~be~written~as~the~product~of~Q~and~a~polynomial~of~degree~<=~N.~This~is~Algori
thm~1~(Procedure~global-bounds)~in~M.~van~Hoeij,~J.-A.~Weil,~'An~algorithm~for~
computing~invariants~of~differential~Galois~groups',~Journal~of~Pure~and~Applie
d~Algebra~117&ndash;118~(1997),~p.~353-379,~https://doi.org/10.1016/S0022-4049(
97)00018-2.FFFF6,FdrFFF5%&fix_LGF6%*ram_indexGF3%'comp_BGF7%-intersect_BrG6#Ffr
FjglFgrt+6'Fh^lF=%$x_0GFi^l>F`^lFa^l6@F]hl%"NG%$solGF`hlF[sFg^l%'symsolGFBF@FA%
"CGFcs%$sysG%$varGFj^l%%solsG%"XG%%symXG%&itempG%$eqnG%%eqnsGF<%#ddG%#ldGFD%#Qs
G%#TxG%#xTGFchlFdhl6"FFCF@$-Fa_l6$FguFc_lYFe_l>8@&FguF\`l>8A&FguF[o>Fa^l7$F]cmF
jbm@%/FhoFe^mC$>8><#/Fc\m*$FjbmF`r>8?<#/Fjbm*$Fc\mF`rC$>Fecm<#/Fc\m,&FjbmFTFhoF
`r>Fjcm<#/Fjbm,&Fc\mFTFhoFT>FI,&-Fhil6#&-F\jl6$-Fcjl6$F]o-Fhjl6#FjbmF`emF[oFTF`
rFT>F^z7#-FO6$FJ/FR;FTFI>&F^zF[oFU>FL-Fiv6%F]oF^zFgu>FY&FLF\`l>FLFjn>Fdfl-Fa_m6
$-Fgt6#-Fd`m6#-Fb]l6#-Fe]l6$FjcmFLFJ>F\p-F\\m6#-F_\m6&F]oFc\m/FjbmFe^mFe\m@%Fbc
m>FW-&F]jl6#%+formal_solG6%F]o/FjbmFho/.%&orderG,&-Fa_m6$,&FdflFTFYF`rFJFTFTFT>
FW-Fdgm6%F]oFhgm/Fjgm,*FYFTFjtFTFdflFTFTFT>FW7#-FO6$-%(convertG6$-Fe]l6$FjcmFew
%(polynomG-%#inG6$FewFW>Fj_l-_I)combinatG6$FgrFaw%)binomialG6$,(FIFTFUFTF`rFT,&
FIFTF`rFT>Fgv-Fgx6#Fj_l>FewFcem>Fbt7#-FO6$&FbtFfoFfem>85F\jm>F\wFT?(FFFTFTFF1F
\wFj_lC&?(FFFTFTFF2&FewF[oFfnC$@$/-Fe_m6$&FewFfoFfemFUC%@%Fbcm>&Fgv6#F\w-Fjhm6$
-%'seriesG6%-%(productG6$)&FWFfoFb[nFfemFc\mF\hmF^im>Ff[n-Fjhm6$-F[\n6%F]\nFc\m
FdhmF^im>&FejmFg[n-F^\n6$)FcjmFb[nFfem>F\w,&F\wFTFTFT>F\[n,&F\[nFTFTFT>F\[nFJ>F
\xFdp?(FFFTFTFF30F\xFT0F\xF`[m@%2&FewFhxFUC$>Fh]n,&Fh]nFTFTFT>F\xFTC$>Fh]nFJ>F
\x,&F\xFTFTFT@%FbcmC$>Fg_l-Fjhm6$-F[\n6%FifmFc\m,&FdflFTFTFTF^im@%/Fg_lFJ>Fgv-F
gx6#7#-FO6$-Fjhm6$-F[\n6%FewFc\mFTF^im-F`im6$FewFgv>Fgv-Fgx6#7#-FO6$-Fjhm6$-F[
\n6%*&FewFTFg_lF`rFc\mFTF^imFe_nC$>Fg_l-Fjhm6$-F[\n6%FifmFc\mFdhmF^im@%Fj^n>Fgv
-Fgx6#7#-FO6$-Fjhm6$-F[\n6%FewFc\m,(FYFTFjtFTFTFTF^imFe_n>Fgv-Fgx6#7#-FO6$-Fjhm
6$-F[\n6%-F[\n6%Fa`nFc\mFdhmFc\mFcanF^imFe_n>F\wFT>F`xF\jm>F`]l7#-FO6$&F`]lFfo/
FR;FTFj_l?(FewFTFTFj_lFjx@%-Fa_l6$-Fb]l6#)&FgvF^xF\p%(ratpolyG>&F`xF^x&F`]lF^x>
FccnFJ>F]yF\jm>F`[l<"?(FewFTFTFj_lFjx@%-Fa_l6$F`cnFacn@%FbcmC$>&F]yF^x-Fe]l6$Fj
cm-Fb]l6#,&-Fe]l6$FecmF`cnFT-Fjhm6$-F[\n6%FfdnFjbmFdqF^imF`r>F`[l-%&unionG6$F`[
l<#FdcnC$>F`dn-Fb]l6#,&F`cnFT-Fjhm6$-F[\n6%F`cnFc\mFdqF^imF`r>F`[lF]enC$>F`dnF`
cn>F`[lF]en>88Fhcn>87-Fjhm6$-F[\n6%-%".G6$-_F_w%*TransposeG6#F]yF`xFc\mFcanF^im
?&FewFafnFjx@%/-Fa_l6$FewFacn%&falseG>F_fn-F^en6$F_fn<#Few@%Fbcm@$2-%(ldegreeG6
$FewFc\m,$FYF`r>F_fnFdgn@$2FY-FgtF\hn>F_fnFdgn>F_fn-F]]m6#F_fn>F_u-Fg[m6$F_fnF`
[l7%-Fe]l6$F_uF`x-Fifl6#*&FLFT-Fe]l6$F_u-Fgfn6$-Fjfn6#-Fe]l6$FecmFgvF`xFT-Fe]l6
$F_u-F_y6#-Fgfn6$-Fjfn6#FejmF`x6#Q_dmLet~'L'~be~a~linear~ordinary~differential~
operator~in~the~differential~algebra~'DD',~'m'~an~integer,~'x_0'~a~point,~and~'
v'~a~number.~The~procedure~inv_heu~returns~a~vector~space~of~candidate~invarian
ts~of~'L'~of~degree~'m'~and~their~corresponding~candidate~values,~given~as~a~pa
rametrized~candidate~vector~invariant,~candidate~value~and~candidate~polynomial
~invariant~in~the~solutions.~This~is~Algorithm~2~(Heuristic~for~computing~invar
iants)~in~M.~van~Hoeij,~J.-A.~Weil,~'An~algorithm~for~computing~invariants~of~d
ifferential~Galois~groups',~Journal~of~Pure~and~Applied~Algebra~117&ndash;118~(
1997),~p.~353-379,~https://doi.org/10.1016/S0022-4049(97)00018-2.FFFF6*FdrFFF(%
.global_boundsGF6Fi`mF/%(makesetG6#""&Fgrt+6$F=F[sF?6"FFC(>FI-Fdim6$,(FUFTF]oFT
F`rFT,&FUFTF`rFT>FLFM>F\p-Fgq6#Fcem>FWFT?(FFFTFTFF1FWFIC&?(FFFTFTFFFinC$@$/-Fe_
m6$FeoFQF]oC$>F[pFL>FWF_p>FjnFap>FjnFJ>FYFdp?(FFFTFTFFFfp@%FjpC$>F[qF_q>FYFTC$>
F[qFJ>FYFdqF\p6#QfuReturn~an~array~of~the~exponents~of~the~monomials~of~degree~
'm'~on~'n'~variables~that~form~a~basis~of~the~'m'-th~symmetric~product~of~the~p
olynomial~ring~on~'n'~variables.FFFF6$FdrFF6#FdpFgrt+6'%"AGF[sF=FCFeam61F@FAFRF
BFjs%"VG%"fGFcsFD%#SAG%"bG%#CsG%#RsGF`hl%#MsG6"FFC*>Few-Fdim6$,(FUFTFhoFTF`rFTF
^[o>F\p7#-FO6$F[p/FWFS>F\x-FbxF^x>F`x-Fgq6#7#-FO6$FJ/FW;FTFew>F`]l-Fgq6#7#-FO6$
-_Feim%,multinomialG6$Fho-%#opG6#&FjtF]pF]_o>F^z7#-FO6$-Fbo6$*&F[pFT&F]o6$FWFLF
TFd^o/FLFS?(F`[lFTFTFewFjx@$0&Fgu6#F`[lFJC$>FI-F_y6#-Fby6$)&F^zF]p&&FjtF[aoF]pF
d^o?(FYFTFTFewFjxC%>&F\x6$FYF`[lFI?(FWFTFTFUFjx>Fiao-Faz6%FiaoF[p&&FjtF\qF]p>Fi
ao-Fb]l6#*&FiaoFT&F`]lF\qF`rF\x6#Qi`lReturn~the~'m'-th~symmetric~power~of~an~'n
'x'n'~matrix~'A'~where~the~basis~of~the~'m'-th~symmetric~power~is~given~by~mono
mials~of~degree~'m'~on~'n'~variables~whose~exponents~are~given~by~the~entries~o
f~'is',~and~'C'~is~an~array~of~length~binomial(n+m-1,n-1)~of~1s~and~0s~with~a~1
~in~the~i-th~entry~if~one~wants~the~i-th~row~of~Sym^m(A)~to~be~computedFFFF6$Fd
rFF6#FejnFgrt+6'Fh^lF=F[sFC>F`^lFa^l6+F@FAFB%"aGFe]oF[bmFDFchlFdhl6"FFC+>Fgv-Fd
im6$F_^o,&FhoFTF`rFT@$FfbmYFe_l>F\wF[cm>FewF^cm>Fa^l7$FewF\w>FI-FbxFcw>F\p&-F\j
l6$-Fcjl6$F]o-FhjlFg[nFcdoF[o?(FLFTFTFgvFjxC$?(FWFTFTFdcoFjxC&>F^zF^bl>Fcao-Fa_
m6$,&FcaoFTF`rFTFJ>&F^z6#F_p,&F^eoFTFTFT?(FYFTFTFgvFjx@$/F`boF^z>&FIF\al&F^blF]
p?(FWFTFTFhoFjxC&>F^zF^bl>&F^z6#Fho-Fa_m6$,&F[foFTF`rFTFJ>Fcao,&FcaoFTFTFT?(FYF
TFTFgvFjx@$Fceo>Feeo,$*(&F^blF\foFTF[pFT&F\p6#,&FhoFTFTFTF`rF`rFI6#Q\hlLet~'L'~
be~a~linear~ordinary~differential~operator~in~the~differential~algebra~'DD'~of~
degree~'n',~'m'~and~integer~and~'is'~an~array~of~the~exponents~of~the~monomials
~in~'n'~variables~that~form~a~basis~of~the~'m'-th~symmetric~power~of~the~polyno
mial~ring~in~'n'~variables.~The~procedure~create_SA~returns~the~matrix~SA~such~
that~if~A~is~the~companion~matrix~of~'L'~and~X~is~a~fundamental~solution~to~X'=
A.X~then~SX:=Sym^m(X)~is~a~fundamental~solution~to~SX'=SA.SX~.FFFF6$FdrFF6#Fejn
Fgrt+6'Fh^lF=F_amFi^l>F`^lFa^l6CF]hlFbamFcamF`hlF[sFg^l%"UGFBF@FAFCFc]o%"WGFc^l
FeamFfamFhamFgamFe]oF[bm%&CtempG%(vartempGF]bmF\bmF<Fiam%#XsGF`bmFDFabmFbbmFchl
Fdhl6"FFCS@$FfbmYFe_l>8CF[cm>8DF^cm>Fa^l7$F_hoF]ho@%FbcmC$>F]cm<#/Fc\m*$F]hoF`r
>8B<#/F]hoF]dmC$>F]cm<#/Fc\m,&F]hoFTFhoF`r>Fiho<#/F]hoFfdm>FI,&-Fhil6#&-F\jl6$-
Fcjl6$F]o-Fhjl6#F]hoF]joF[oFTF`rFT>FjbmFcim>F`x-Fiv6$FUFI>F^zFcem>FL-Fgq6#7#-FO
6$FJ/FR;FTFjbm>FjcmFejo>FYFejo>Fj_lFejo>FiemFU>Fjn-F\\mF\fm>Fi[m&FjnF\`l>Fjn&Fj
nF[o@%Fbcm>&Fj_lF[o-Fa_m6$-Fgt6#-Fd`m6#-Fb]l6#-Fe]l6$FihoFjnFJ>Fh[pFi[p?(FewFdp
FTFjbmFjxC&>&FLF^x-F\\m6%F]oFccnFgu>&FYF^x&Fg\pF\`l>Fg\p&Fg\pF[o@%Fbcm>&Fj_lF^x
-Fa_m6$-Fgt6#-Fd`m6#-Fb]l6#-Fe]l6$FihoFg\pFJ>Fa]pFb]p>F\p-F]]m6#-F_\m6&F]oFc\m/
F]hoFe^mFe\m@%Fbcm>FW-Fdgm6%F]o/F]hoFho/Fjgm,(-Fa_m6$,&-Fa_mF]jmFT-F^^mF\qF`rFJ
FTFIFTFTFT>FW-Fdgm6%F]oFg^p/Fjgm,(-Fa_mF\qFTFIFTFTFT>F]y-FbxFgy@%Fbcm?(FewFTFTF
IFjx?(F\xFTFTFIFjx>&F]y6$FewF\x-Fjhm6$-F[\n6%-Fe]l6$Fiho-F^al6$-Fjhm6$&FWFhxF^i
m7#-%"$G6$F]ho,&FewFTF`rFTFc\m,&Fj^pFTFTFTF^im?(FewFTFTFIFjx?(F\xFTFTFIFjx>F[`p
-Fjhm6$-F[\n6%Fa`pFc\m,&Fd_pFTFTFTF^im>F`[l-Fjfn6#Fejo>FecmFgap>F`]l-Fa]m6'F]oF
UFhoFjtFgu>&F`[lF[o&F`]lF\`l>&FecmF[o&F`]l6#Ffr>F`]l&F`]lF[o>FejmFhcn?&FewF`]lF
jx@$-Fa_l6$Few%(indexedG>Fejm-F^en6$FejmFfgn>Fejm-T-F^jn>Fgv-T/6+F]yFYFUFIFhoFj
tF`xF`]lFj_l>Fg_l-T16&FIFUF`xF`]l>F_uFgap@%Fbcm?(FewFdpFTFjbmFjxC(>&FjcmF^x-Fjh
m6$-F[\n6%Fj]pFc\m,&Fa]pFTFTFTF^im@%/F_dpFJ>&F_uF^x-Fjhm6$-F[\n6%-Fgfn6$F`cnF`]
lFc\mFTF^im>Fhdp-Fjhm6$-F[\n6%*&F]epFTF_dpF`rFc\mFTF^im>&F`[lF^x*&-Fe]l6$F]cmFh
dpFTFg\pFT>&FecmF^x-Fgfn6$&Fg_lF^xF`]l>FdalFhcn?&F\wFhdpFjx@$/-Fa_l6$F\wFacnFbg
n>Fdal-F^en6$Fdal<#F\w?(FewFdpFTFjbmFjxC(>F_dp-Fjhm6$-F[\n6%Fj]pFc\m,(F[]pFTFa]
pFTFTFTF^im@%Ffdp>Fhdp-Fjhm6$-F[\n6%F]epFc\m,&F[]pFTFdpFTF^im>Fhdp-Fjhm6$-F[\n6
%-F[\n6%FdepFc\mF`gpFc\m,&F[]pFTFTFTF^im>FfepFgep>F[fpF\fp>FdalFhcn?&F\wFhdpFjx
@$Fbfp>FdalFffp>Fdal-Facp6#Fdal>Fbt-Fg[m6$FdalFejm>F`[l-Fe]l6$FbtF`[l>Fecm-Fe]l
6$FbtFecm>F`]l-Fe]l6$FbtF`]l>FejmFhcn?&FewF`]lFjx@$Fibp>FejmF]cp>FejmF`cp>86-T3
6&F]oFUFIF`x>Fbt-Fg[m6$<#-FO6$,&-F^al6$&F`[lFfoF]hoFT&-Fgfn6$F[jpF`[lFfoF`rFjjo
Fejm>F`[lF]ip>FecmF`ip7%F`[lFecmF`]l6#QaglLet~'L'~be~a~linear~ordinary~differen
tial~operator,~'m'~an~integer,~'x_0'~a~point~and~'v'~a~number.~The~procedure~in
variants~returns~the~space~of~invariants~in~dual,~polynomial~and~vector~forms.~
This~is~Algorithm~3~(Algorithm~Invariants)~in~M.~van~Hoeij,~J.-A.~Weil,~'An~alg
orithm~for~computing~invariants~of~differential~Galois~groups',~Journal~of~Pure
~and~Applied~Algebra~117&ndash;118~(1997),~p.~353-379,~https://doi.org/10.1016/
S0022-4049(97)00018-2.FFFF64FdrFFF*%*create_isGF(FbjnF6Fi`mF)%(inv_heuGF/FcjnF8
%)create_UGF9%)create_XGF,%*create_SAG6#FejnFgr-t,6#'%"SG%$setG6&%"sGFBF<%$SetG
6"FFC%>F\pFhcn?&FLF]oFjxC%>FWFT?&FYF\pFjx@$/FLFY>FWFJ@$/FWFT>F\p-F^en6$F\p<#FLF
\p6#Qjnmake~a~set~from~S,~because~MAPLE~seems~to~have~issues~with~thatFFFF6$Fdr
FF6#FTF\\qFFt+6#'F^hlFjglFF6"FF@%/-F[hn6#&F]oF[oFe^mFJ*&Fj]qFT-Fgt6#-%$lhsG6#&F
]oF\`lF`r6#Q8compute~valuation~primeFFFF6$FdrFF6#FTFFt,6$'Fa]oF\\q'FahlF\\q6#F[
\q6"FFC$>FL<#-FO6$-FO6$-Fb]l6#,&F@FTFAFT-F`im6$F@F]o-F`im6$FAFU-FivFb`l6#Q3comp
ute~sumset~A+BFFFF6&FdrFFF/Fcjn6#FdpF\\qFFt,6$Fj^q'F[s%(integerG6$F@%%NsetG6"FF
C%>FY<#FJ?(FLFTFTFUFjx>FY-Fiv6$FYF]oFY6#Q0compute~set~n.AFFFF6&FdrFFF1%'sumsetG
6#FdpF\\qFFt,6%FcsFc`qFigl6'Fahl%#BiGF@F=F[\q6"FFC)>FY7#-FO6#FS>F\p-FhilFg`l?(F
WFTFTFUFjxC$>FI-FO6$,*&F]o6$FBFTFT*&F_rFT-Fiv6#&F]o6#FBFTFTFWF`rFTFT/FB;FTF\p>&
FYF]p-F\\m6#<#FI?(FWFTFTFUFjx@%/&FhoF]pFJ>F`cqFj`q>F`cq-F]]m6$F`cqFgcq>FLFj`q?(
FWFTFTFUFjx>FL-Fa]m6$FLF`cqFL6#QBcompute~the~set~B~from~Theorem~25FFFF6,FdrFFF0
%$valGF/FcjnF2%%nsetGF1Fbaq6#FfrF\\qFFt+6#'FcsFjgl6$F<F@6"FFC%>FLFJ?&FYF]oFjx>F
L-%$gcdGF\alFL6#Q=compute~gcd~of~elements~in~lFFFF6$FdrFF6#FTFFt+6$Fh^lF`^l6%%$
L_0GFchlFdhl6"FFC'>FY&FUF\`l>FW&FUF[o>Fa^l7$FWFY>FL-&F]jl6#%%multG6$-Fhdl6#-Fj_
o6#-F]el6#&-F\jl6$-Fcjl6$F]o-FhjlF\qFcgqF[oF]o-Fdfq6$*$-Fiv6#&-F\jl6$-Fcjl6$FLF
cgqFcgqF[oF`rFL6#Q6(ii)~of~global~boundsFFFF6&FdrFFF4%%mgcdG6#FdpFFt+6#Fcs6(F`h
lF@F<FBF^\qF[\q6"FFC&>FLFhcn>F^z-FO6$-Fgt6#-Fa^q6#&FYF\`l-F`imF^aq?&FIF^zFjxC%>
FWFT?&F\pFLFjx@$/FIF\p>FWFJ@$F[]q>FL-F^en6$FLFccq-Fhdl6#-Fj_oFb`l6#Q?compute~th
e~ramification~indexFFFF6$FdrFF6#FTFFt,6$FahlF`hl6$F@F[\q6"FFC%>FYFhcn?&FLF]oFj
x@$/*&FUFTFLFT*&FUFT-%&floorGFb`lFT>FY-F^en6$FYF_]q-FivF\q6#Q3intesect~B~and~Z/
rFFFF6&FdrFFF/Fcjn6#FdpF\\qFFt+6+FdgoFbamF=F[sF_amFi^lFCFeamF<61F@FAFRFcgoFBFc]
oFjsFcsFDFg^lFf]oFg]oFh]oF`hlFi]o6"FFC*>Few-Fdim6$,(FjtFTFhoFTF`rFT,&FjtFTF`rFT
>F\pFf^o>FI7#-FO6$&FIF]p/FW;FTFjt>F^z7#-FO6$-Fbo6$*&Fh\rFTFd`oFTFi\r/FLFj\r>F`x
Fh^o>F`]l-Fgq6#7#-FO6$-Ff_o6$Fho-Fj_o6#&9*F]pF]_o@%/FguFe^m?(F`[lFTFTFewFjx@$0&
9+F[aoFJC$>Fgv-F_y6#-Fjhm6$-F[\n6%-Fby6$)Fcao&&F_^rF[aoF]pFi\rFc\m,(-Fa_m6$,&9,
FTFUF`rFJFTFjtFTFTFTF^im?(FYFTFTFewFjxC%>&F\pFjaoFgv?(FWFTFTFjtFjx>F\`r-Faz6%F
\`rFh\r&&F_^rF\qF]p>F\`r-Fb]l6#*&-Fjhm6$-F[\n6%F\`rFc\m,(&Fh_rF\qFT&FUF\qF`rFTF
TF^imFTFeboF`r?(F`[lFTFTFewFjx@$Fd^rC$>Fgv-F_y6#-Fjhm6$-F[\n6%F__rFc\m,(-Fa_m6#
,&FUFTFh_rFTFTFjtFTFTFTF^im?(FYFTFTFewFjxC%>F\`rFgv?(FWFTFTFjtFjx>F\`rF_`r>F\`r
-Fb]l6#*&-Fjhm6$-F[\n6%F\`rFc\m,(F]arFTF\arFTFTFTF^imFTFeboF`rF\p6#Q0create~Sym
^m(W)FFFF6$FdrFF6#""*FFt+6&F[sF=FCFeam6'F@FAF^sFiamFd]o6"FFC%>FIf*6$F@FAFF6$%)o
peratorG%&arrowGFF&T#6$F]oFUFFFF6$FiamF\p>FW-Fbx6$F]oFI>F\p-Fiv6'F\pF]oFUFhoFjt
6#Q4create~matrix~of~XsFFFF6&FdrFFF+%+create_SymG6#""%FFb6#%+thismoduleGF.6#%(p
ackageGF$FF6#QbpTools~for~studying~linear~ordinary~differential~equations~with~
only~algebraic~solutionsFFFFFFFFFF
